default_language_version:
  python: python3.11

default_stages:
  - commit
  - push

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        additional_dependencies:
          - "tomli"

  # Python specific

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.5
    hooks:
      - id: pycln

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - --target-version
          - py310

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        exclude: "test_*"
        args: ["-iii", "-ll", "-s=B308,B703"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.277
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/python-poetry/poetry
    rev: "1.5.0" # add version here
    hooks:
      - id: poetry-check
      - id: poetry-export

  # Commitizen
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.2
    hooks:
      - id: commitizen

  # Sort __all__ variables
  - repo: https://github.com/aio-libs/sort-all
    rev: v1.2.0
    hooks:
      - id: sort-all
