[tool.poetry]
name = "scw-registry-cleaner"
version = "0.1.0"
description = "Clean docker images from scaleway registry"
authors = ["gazorby <gazorby@pm.me>"]
license = "MIT"
readme = "README.md"
packages = [{include = "scw_registry_cleaner"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
